#TODO create a detection utility
set(HAVE_WIN_SOCKETS           1)

if (MSVC)
	#set (OPENSSL_CFLAGS			-DOPENSSL_NO_SHA256 -DOPENSSL_NO_SHA512)
	#set (OPENSSL_CFLAGS			"-DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -DDSO_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -DOPENSSL_USE_APPLINK -DOPENSSL_NO_CAMELLIA -DOPENSSL_NO_SEED -DOPENSSL_NO_RC5 -DOPENSSL_NO_MDC2 -DOPENSSL_NO_TLSEXT -DOPENSSL_NO_CMS -DOPENSSL_NO_KRB5 -DOPENSSL_NO_DYNAMIC_ENGINE")
	set (OPENSSL_CFLAGS "")
	set (OPENSSL_LIBS			libeay32 ssleay32 ${RESOLV_LIBS})
	set (ICU_LIBS)
else ()
	set (ICU_LIBS				icudt icuuc)
	set (OPENSSL_LIBS			libeay32 libssl32)
endif ()
